dist: xenial
language: python
matrix:
  include:
    - name: "Python 3.7.3 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install: python3 --version; pip3 --version; sw_vers
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
install: 
  - pip3 install --upgrade pip
  - pip install -r requires.txt
  - pip install codecov
  - pip install -i https://test.pypi.org/simple/ sudsoln
env:
  - CODECOV_TOKEN="8b15563c-3721-44a3-b8a0-15362e28ec0f"
after_success:
  - coverage run sudsoln/tests.py
  - codecov
notifications:
  email: false