language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install: 
  - pip install -r requires.txt
  - pip install codecov
script: 
  - python sudsoln/tests.py
env:
  - CODECOV_TOKEN="8b15563c-3721-44a3-b8a0-15362e28ec0f"
after_success:
  - coverage run sudsoln/tests.py
  - codecov
